index:
  credentials: [[edit_disciplinary_sanction_type, new_disciplinary_sanction_type]]

new:
  credentials: [new_disciplinary_sanction_type]

create:
  credentials: [new_disciplinary_sanction_type]

edit:
  credentials: [edit_disciplinary_sanction_type]

update:
  credentials: [edit_disciplinary_sanction_type]

delete:
  credentials: [new_disciplinary_sanction_type]

