generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           Tag
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tag
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        title: Tags
        display: [name]
        object_actions:
          _edit:
          _delete:
        batch_actions: []
      filter:
        class: false
      form:    ~
      edit:
        title: Edit tag
      new:
        title: New tag
