generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           Tag
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tag
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        title: Tags
        display: [name]
        object_actions:
          _edit:
          _delete:
            condition: canBeDeleted
        batch_actions: []
        actions:
          _new:
            label: Nueva etiqueta
      filter:
        class: false
      form:    ~
      edit:
        title: Edit tag
        actions:
          _list:
            label:          Volver al listado
          _save_and_list:
            label:          Guardar etiqueta
      new:
        title: New tag
        actions:
          _list:
            label:          Volver al listado
          _save_and_list:
            label:          Guardar etiqueta
          _save_and_add:
            label:          Guardar y agregar otra etiqueta
