generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           AbsenceType
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          absence_type
    with_propel_route:     1

    config:
      actions: ~
      fields:
        value:
          label:           Valor
      list:
        peer_method:       doSelectOrder
        title:             Tipos de ausencias
        display:           [name, value ,method_str, _order, description]
        object_actions:
          _edit:
            credentials:   [edit_absence_type]
          _delete:
            credentials:   [new_absence_type]
            condition:     canBeDeleted
        batch_actions:     []
        actions:
          _new:
            label:         Nuevo tipo de ausencia
            credentials:   [new_absence_type]
      filter:
        class:             false
      form:
      edit:
        title: Editar tipo de ausencia
        actions:
          _list:
            label:         Volver al listado
          _save_and_list:
            label:         Guardar tipo de ausencia
      new:
        title: Nuevo tipo de ausencia
        actions:
          _list:
            label:         Volver al listado
          _save_and_list:
            label:         Guardar tipo de ausencia
          _save_and_add:
            label:         Guardar y agregar otro tipo de ausencia