prod:
  logger:
    class: sfAggregateLogger
    param:
      level: err
      loggers:
        sf_file_debug:
          class: sfConsoleLogger
          param:
            level: err

cli:
  controller:
    class: sfConsoleController
  request:
    class: sfConsoleRequest
  response:
    class: sfConsoleResponse

test:
  storage:
    class: sfSessionTestStorage
    param:
      session_path: %SF_TEST_CACHE_DIR%/sessions

  response:
    class: sfWebResponse
    param:
      send_http_headers: false

all:
  routing:
    class: sfPatternRouting
    param:
      generate_shortest_url:            true
      extra_parameters_as_query_string: true

  mailer:
    class: sfMailer
    param:
      logging:           %SF_LOGGING_ENABLED%
      charset:           %SF_CHARSET%
      delivery_strategy: realtime
      transport:
        class: Swift_SmtpTransport
        param:
          host: <?php echo $_ENV['MAIL_HOST']; ?>

          port: <?php echo $_ENV['MAIL_PORT']; ?>


  user:
    class: myUser
    param:
      timeout:         3600
      logging:         %SF_LOGGING_ENABLED%
      use_flash:       true
      default_culture: es_AR
  i18n:
    class: pmI18N

  storage:
    class: sfCacheSessionStorage
    param:
      cache:
        class: sfMemcacheCache
        param:
          servers:
            localservers:
              host: <?php echo $_ENV['MEMCACHE_HOST']; ?>

              port: <?php echo $_ENV['MEMCACHE_PORT']; ?>

      session_name: <?php echo $_ENV['SESSION_NAME']; ?>
