rendering: ~
security:  ~
change_password:
  class: sfGuardChangePasswordFilter
login_filter:
  class: loginFilter
state:
  class:  dcStatefulSecurityFilter
  param:
    default_policy: allow

save_output:
  class: saveOutputFilter
  
pm_pdfkit:
  class: pmPDFKitFilter

cache:     ~
common:    ~
execution: ~
