generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           Study
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          study
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        title: Listado de estudios cursados
        batch_actions:      []
        display: [name]
        object_actions:
          _edit:
            credentials: [edit_study]
          _delete:
            credentials: [edit_study]
            condition:    canBeDeleted
        actions:
          _new:
            credentials: [edit_study]
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
