generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           ExaminationRepproved
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          examination_repproved
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        batch_actions: []
        layout: stacked
        params: |
          %%_information%%
        display: [examination_repproved]
        object_actions:

          _edit:
            credentials:  [edit_examination_repproved]
            condition: canEdit

          subjects:
            label: Subjects
            action: examinationRepprovedSubjects
            credentials:  [show_examination_repproved_subjects]

          _delete:
            credentials:  [edit_examination_repproved]
            condition: canDelete

        actions:

          back:
            action: back
            label:        Volver al listado años lectivos

          _new:
            condition: canCreateExaminationRepproved
            credentials:  [edit_examination_repproved]

      filter:
        class: false
      form:    ~
      edit:
        title:  Edit repproved examination
        actions:
          _list:
          _save_and_list:
      new:
        title:  New repproved examination
        actions:
          _list:
          _save_and_list:
          _save_and_add:
