examinationRepprovedSubjects:
  credentials: [show_examination_repproved_subjects]

index:
  credentials: [show_examination_repproved]

new:
  credentials: [edit_examination_repproved]

create:
  credentials: [edit_examination_repproved]

edit:
  credentials: [edit_examination_repproved]

update:
  credentials: [edit_examination_repproved]

delete:
  credentials: [edit_examination_repproved]

