examinations:
  credentials:  [show_examination]

examinationRepproved:
  credentials:  [show_examination_repproved]

index:
  credentials: [show_school_year]

new:
  credentials: [edit_school_year]

create:
  credentials: [edit_school_year]

show:
  credentials: [show_school_year]

delete:
  credentials: [edit_school_year]

changeState:
  credentials: [edit_school_year]

registeredStudents:
  credentials: [show_school_year]

schoolYearCareers:
  credentials: [show_school_year]