generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           Shift
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          shift
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        title:              Listado de turnos
        batch_actions:      []
        display:            [name]
        object_actions:
          _edit:
            credentials: [edit_shift]
          _delete:
            credentials: [edit_shift]
        actions:
          _new:
            label: Nuevo turno
            credentials: [edit_shift]

      filter:
          class: false
      form:    ~
      edit:
        title:              Editar turno
        actions:
          _list:
            label:          Volver al listado de turnos
          _save_and_list:
            label:          Guardar turno

      new:
        title:              Nuevo turno
        actions:
          _list:
            label:          Volver al listado de turnos
          _save_and_list:
            label:          Guardar turno
          _save_and_add:
            label:          Guardar y agregar otro turno