generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           Student
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          student_stats
    with_propel_route:     1

    config:
      actions: ~
      exportation:
        enabled: true
        title: Student list
        type: xls
        fieldSelection:
          lastname:
            label: Lastname
            method: getPersonLastname
            decorator: text
          person_firstname:
            label: Firstname
            method: getPersonFirstname
            decorator: text
          person_identification_type:
            label: Identification type
            method: getPersonIdentificationTypeString
            decorator: text
          person_identification_number:
            label: Identification number
            method: getPersonIdentificationNumber
            decorator: text
          person_email:
            label: Email
            method: getPersonEmail
            decorator: text
          person_phone:
            label: Phone
            method: getPersonPhone
            decorator: text
          person_address:
            label: Address
            method: getPersonAddress
            decorator: text
          division:
            label: Division
            method: getDivisionFromStudentStatsFilters
            decorator: text
          shift:
            label: Shift
            method: getShiftFromStudentStatsFilters
            decorator: text
          career_school_year:
            label: Career
            method: getCareerFromStudentStatsFilters
            decorator: text

      fields:
        person:
        person_lastname:  { label: Lastname, column_name: PersonPeer::LASTNAME }
        person_firstname: { label: Firstname, column_name: PersonPeer::FIRSTNAME }
        careers:          { label: Careers}
        person_full_identification:       { label: Identification number, column_name: PersonPeer::IDENTIFICATION_NUMBER }

      list:
        title:              Student list
        peer_method:        doSelectJoinPerson
        actions:
        batch_actions: []
        display: [person_lastname, person_firstname, person_full_identification, career, division, shift]
        layout: stacked
        params: |
          %%_student_info%%
        sort: [ person_lastname ]
        object_actions: []
        actions:
          _user_export:

      filter:
        class: StatsStudentFormFilter
      form:    ~
      edit:    ~
      new:     ~