generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           StudentFree
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          student_free
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        display:  [career_school_year ,career_school_year_period, course_subject, is_free]
        object_actions:

          _edit:
            credentials:  [set_free]

          _delete:
            credentials:  [set_free]

        batch_actions:  []
        actions:
          _back:
            action: back
          _new:
            credentials:  [set_free]
      filter:
        class:  false
      form:    ~
      edit:
        actions:
          _back:
          _save_and_list:
      new:
        actions:
          _back:
          _save_and_list:
