generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           StudentReincorporation
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          student_reincorporation
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        batch_actions: []
        object_actions:

          _edit:
            credentials:  [edit_student_reincorporation]
            condition: canEdit

          _delete:
            credentials: [edit_student_reincorporation]
            condition: canEdit
        display:  [reincorporation_days, observation, created_at]
        actions:
          back:
            action: back
          _new:
            credentials: [edit_student_reincorporation]
      filter:
        class:  false
      form:    ~
      edit:
        actions:
          _list:
            label: Volver
          _save_and_list:
            label: Guardar reincorporación

      new:
        actions:
          _list:
            label: Volver
          _save_and_list:
            label: Guardar reincorporación
