generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           Personal
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          head_personal
    with_propel_route:     1

    config:
      actions: ~
      fields:
        person:
        person_lastname:                    { label: Lastname, column_name: PersonPeer::LASTNAME }
        person_firstname:                   { label: Firstname, column_name: PersonPeer::FIRSTNAME }
        person_full_identification:       { label: Identification number, column_name: PersonPeer::IDENTIFICATION_NUMBER }
        person_sf_guard_user:             { label: Username}
        person_is_active:    { label: Activo, type: Boolean }
      list:
        peer_method:       doSelectJoinAll
        display:           [ person_lastname, person_firstname, person_full_identification, person_is_active, person_sf_guard_user, phone, email  ]
        sort: [ person_lastname ]
        batch_actions:     []
        object_actions:

          _show:
            credentials:   [show_head_personal]

          _edit:
            credentials:   [edit_head_personal]

          _delete:
            credentials:   [edit_head_personal]

          preceptors:
            label:  Asignar preceptores
            credentials:   [edit_head_personal]
            action: preceptors

          activate:
            label: Set active
            credentials: [edit_head_personal]
            action: personActivation
            condition: canPersonBeActivated

          deactivate:
            label: Set inactive
            credentials: [edit_head_personal]
            action: personActivation
            condition: canPersonBeDeactivated
            params: confirm='Are you sure?'

        actions:
          _new:
            credentials:   [edit_personal]
            label:         Nuevo jefe de preceptores
      filter:
       class: false
      form:    ~
      edit:
        title: Editar jefe de preceptores
        actions:
          _list:
            label:         Volver al listado
          _save_and_list:
            label:         Guardar jefe de preceptores
      new:
        title: Nuevo jefe de preceptores
        actions:
          _list:
            label:         Volver al listado
          _save_and_list:
            label:         Guardar jefe de preceptores
          _save_and_add:
            label:         Guardar y agregar otro jefe de preceptores
      show:
        title:  Detalles del jefe de preceptores
        display:
          Datos personales:           [_person]
          Datos postales:             [_address]
          Datos institucionales:      [file_number, salary, aging_institution]
        actions:
          _list:
            label:               Volver al listado
