index:
  credentials: [new_tutor_type]

new:
  credentials: [new_tutor_type]

create:
  credentials: [new_tutor_type]

edit:
  credentials: [new_tutor_type]

update:
  credentials: [new_tutor_type]

show:
  credentials: [new_tutor_type]

delete:
  credentials: [new_tutor_type]
