generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           Personal
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          personal
    with_propel_route:     1

    config:
      actions: ~
      exportation:
        enabled: true
        title: Personal list
        type: xls
        fieldSelection:
          lastname:
            label: Lastname
            method: getPersonLastname
            decorator: text
          person_firstname:
            label: Firstname
            method: getPersonFirstname
            decorator: text
          person_identification_type:
            label: Identification type
            method: getPersonIdentificationTypeString
            decorator: text
          person_identification_number:
            label: Identification number
            method: getPersonIdentificationNumber
            decorator: text
          person_email:
            label: Email
            method: getPersonEmail
            decorator: text
          person_phone:
            label: Phone
            method: getPersonPhone
            decorator: text
          person_address:
            label: Address
            method: getPersonAddress
            decorator: text
      fields:
        #necesario para que no se cuelque el list
        person:
        person_lastname:                    { label: Lastname, column_name: PersonPeer::LASTNAME }
        person_firstname:                   { label: Firstname, column_name: PersonPeer::FIRSTNAME }
        person_full_identification:       { label: Identification number, column_name: PersonPeer::IDENTIFICATION_NUMBER }
        person_sf_guard_user:             { label: Username}
        person_is_active:    { label: Activo, type: Boolean }
#        aging_institution:            {label:  Fecha de inicio en la institución}
#        salary:                       {label:  Salario}


      list:
        title:             Listado de preceptores
        peer_method:       doSelectJoinAll
        display:           [ person_lastname, person_firstname, person_full_identification, person_is_active, person_sf_guard_user, phone, email  ]
        sort: [ person_lastname ]
        batch_actions:     []

        object_actions:
          _show:
            credentials:   [show_personal]
          _edit:
            credentials:   [edit_personal]
          _delete:
            condition: canBeDeleted
            credentials:   [edit_personal]

          licenses:
            label:  Licenses
            action: licenses
            credentials: [edit_license]

          aggregate_profesor:
            label:  Aggregate as a teacher
            action: aggregateAsTeacher
            condition:  canAddTeacher
            credentials:  [edit_personal]

          activate:
            label: Set active
            credentials: [edit_personal]
            action: personActivation
            condition: canPersonBeActivated

          deactivate:
            label: Set inactive
            credentials: [edit_personal]
            action: personActivation
            condition: canPersonBeDeactivated

        actions:
          _new:
            label:         Nuevo preceptor
            credentials:   [edit_personal]
          _user_export:

      filter:

      form:     ~

      edit:
        title:                   Edición de preceptor "%%person%%"
        actions:
          _list:
            label:               Volver al listado de preceptores
          _save_and_list:
            label:                Guardar y volver al listado de preceptores

      new:
        title:             Nuevo preceptor
        actions:
          _list:
            label:               Volver al listado de preceptores
          _save_and_list:
            label:                Guardar y volver al listado de preceptores
          _save_and_add:
            label:                Guardar y agregar otro preceptor

      show:
        title:        Detalle del preceptor "%%person%%"
        display:
          Datos personales:           [_person]
          Datos postales:             [_address]
          Datos institucionales:      [file_number, salary, aging_institution]
          Licencias:                  [_licenses]
        actions:
          _list:
            label:               Volver al listado de preceptores
