index:
  credentials: [show_personal]

new:
  credentials: [edit_personal]

create:
  credentials: [edit_personal]

edit:
  credentials: [edit_personal]

update:
  credentials: [edit_personal]

show:
  credentials: [show_personal]

delete:
  credentials: [edit_personal]

personActivation:
  credentials: [edit_personal]
