generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           FinalExaminationSubject
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          final_examination_subject
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        layout: stacked
        params: |
          %%_information%%
        display: [Subjects]
        object_actions:

          _edit:
            credentials: [edit_final_examination_subject]
            condition: canBeEdited

          _students:
            action: students
            condition:  canAddStudents
            label:  Students
            credentials: [edit_final_examination_subject_students]

          califications:
            action: califications
            credentials: [edit_final_examination_subject_califications]
            condition: canCalificate

          close:
            action: close
            condition: canBeClosed
            label: Close examination
            credentials: [edit_final_examination_subject]

          _delete:
            credentials: [edit_final_examination_subject]
            condition: canDelete
        
        batch_actions: []
        actions:

          back:
            action: back
            label:  Volver al listado de mesas de previa
            
          _new:
            credentials: [edit_final_examination_subject]
            label:  Nueva mesa de final

      filter:
        class:  false        
      form:    ~
      edit:    ~
      new:     ~
