generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           Holiday
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          holiday
    with_propel_route:     1

    config:
      actions: ~
      fields:
        day:
          date_format: 'dd/MM/yyyy'
      list:
        title: Holidays
        display: [day, description]
        object_actions:
          _edit:
          _delete:
        batch_actions: []
        actions:
          _new:
            label: Nuevo día feriado
      filter:  ~
      form:    ~
      edit:
        actions:
          _list:
            label:         Volver al listado
          _save_and_list:
            label:         Guardar día feriado
      new:
        actions:
          _list:
            label:         Volver al listado
          _save_and_list:
            label:         Guardar día feriado
          _save_and_add:
            label:         Guardar y agregar otro día feriado