default:
  http_metas:
    content-type: text/html

  metas:
    title:         Escuela M.C y M.L Inchausti
    description:   Escuela M.C y M.L Inchausti
    keywords:      Inchasuti, Cespi, unlp, alumnos
    language:      es_AR
    #robots:       index, follow

  stylesheets:    [main.css, smoothness/jquery-ui-1.7.2.custom.css, /pmJSCookMenuPlugin/css/ThemePanel/theme.css]

  javascripts:    [jquery.js, jquery-ui.js, jquery.cookie.js, no-conflict.js, /sfProtoculousPlugin/js/prototype.js, main.js, jquery.notification.js, i18n/ui.datepicker-es.js, /pmJSCookMenuPlugin/js/JSCookMenu.js, /pmJSCookMenuPlugin/js/ThemePanel/theme.js]

  has_layout:     on
  layout:         layout
