generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           OccupationCategory
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          occupation_category
    with_propel_route:     1

    config:
      actions: ~
      fields:               
      list:
        title: Listado de categorias ocupacionales
        batch_actions:      []
        display: [name]
        object_actions:
          _edit:
            credentials: [edit_occupation]
          _delete:
            credentials: [edit_occupation]
            condition:    canBeDeleted
        actions:
          _new:
            label: Nueva categoria ocupacional
            credentials: [edit_occupation]
      filter:
        class: false
      form:
      edit:
        actions:
          _list:
            label:         Volver al Listado
          _save_and_list:
            label:         Guardar categoria ocupacional
      new:
        actions:
          _list:
            label:         Volver al Listado
          _save_and_list:
            label:         Guardar categoria ocupacional
          _save_and_add:
            label:         Guardar y agregar otra categoria ocupacional
