index:
  credentials: [show_pathway]

new:
  credentials: [edit_pathway]

create:
  credentials: [edit_pathway]

show:
  credentials: [show_pathway]

delete:
  credentials: [edit_pathway]
  
edit:
  credentials: [edit_pathway]

update:
  credentials: [edit_pathway]