#!/bin/sh
 set -eo pipefail

source /usr/local/bin/setenvdefaults

echo -e "expose_php = Off\n"\
	"date.timezone = $TIMEZONE\n"\
        "memory_limit = $MEMORY_LIMIT\n"\
        "max_execution_time = $MAX_EXECUTION_TIME\n" > /usr/local/etc/php/conf.d/php.ini

envsubst '${DB_NAME} ${DB_HOST} ${DB_USERNAME} ${DB_PASSWORD}' < /app/config/propel.ini.docker > /app/config/propel.ini


echo 'SetEnvIf Request_URI "^/robots.txt$" dontlog' > /etc/apache2/conf.d/docker.conf
echo 'CustomLog logs/access.log combined env=!dontlog' >> /etc/apache2/conf.d/docker.conf 
echo 'ServerTokens Prod' >> /etc/apache2/conf.d/docker.conf 
echo 'ServerSignature Off' >> /etc/apache2/conf.d/docker.conf 

CMD='cd /app && rm -fr cache/* && ./symfony propel:build-all --classes-only && ./symfony plugin:publish && ./symfony fix-perms && ./symfony kimkelen:flavor $FLAVOR'

if [ -z "$APACHE_RUN_USER" ]; then
  sh -c "$CMD"
else
  su $APACHE_RUN_USER -c "$CMD"
fi

exec /usr/local/bin/original-docker-php-entrypoint "$@"
