index:
  credentials: [show_teacher]

new:
  credentials: [edit_teacher]

create:
  credentials: [edit_teacher]

edit:
  credentials: [edit_teacher]

update:
  credentials: [edit_teacher]

show:
  credentials: [show_teacher]

delete:
  credentials: [edit_teacher]

personActivation:
  credentials: [edit_teacher]
