generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           HealthCoverage
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          health_coverage
    with_propel_route:     1

    config:
      actions: ~
      fields: ~
      list:
        title: Listado de obras sociales
        display:           [=name]
        actions:
          _new:
            credentials: [new_health_coverage]
            label: Nueva obra social
        batch_actions: []
        object_actions:
          _edit:
            credentials: [new_health_coverage]
          _delete:
            credentials: [new_health_coverage]
            condition: canBeDeleted
      filter:
        class:  false
      form: ~
      edit:
        title: Editar obra social
        actions:
          _list:
            label: Volver al listado de obras sociales
          _save_and_list:
            label:        Guardar y volver al listado de obras sociales
      new:
        title: Nueva obra social
        actions:
          _list:
            label: Volver al listado de obras sociales
          _save_and_list:
            label:        Guardar y volver al listado de obras sociales
          _save_and_add:
            label:        Guardar y agregar otra obra social
      show: ~
