generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           FinalExamination
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          final_examination
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        batch_actions: []
        layout: stacked
        params: |
          %%_information%%
        display: [final_examination]
        object_actions:
          _edit:
            credentials: [edit_final_examination]

          examination_subjects:
            label: Subjects
            action: subjects
            credentials: [show_final_examination_subject]

          _delete:
            credentials: [edit_final_examination]
        actions:
          back:
            action: back
            label:      Volver a listado de años lectivos
            
          _new:
            condition: canCreateFinalExamination
            credentials: [edit_final_examination]
            label:      Nueva mesa de final

      filter:
        class:  false
      form:    ~
      edit:    ~
      new:     ~
