# this options will be accessable throught sfConfig::get with a name prefix: sf_phpunit_*

all:
  
  selenium:
    driver:
      browser: '*firefox'
      browser_url: 'http://localhost'
      timeout: 10
      http_timeout: 10
