connection: propel
description: Modelo de datos del Sistema de alumnos

classes:

  Department:
    tablename: department
    description:  Representa el partido/departamento de una provincia
    columns:
      id:
      name:
        type: varchar(255)
      state_id:
        type: integer
        foreignClass: state
        foreignReference: id
        required: true
      _indexes:
        state: [state_id]
        name: [name]

  City:
    tableName:            city
    description:          Representa una ciudad
    columns:
      id:
      name:
        type: varchar(255)
        required: true
      short_name:
        type: varchar(255)
      department_id:
        type: integer
        foreignTable: department
        foreignReference: id
        required: true
      _indexes:
        department: [department_id]
        name: [name]

  Country:
    tableName:            country
    description:          Representa un País
    columns:
      id:
      name:
        type: varchar(255)
        required: true
      nationality:
        type: varchar(255)
        required: true

  State:
    tableName:            state
    description:          Representa una provincia
    columns:
      id:
      name:
        type: varchar(255)
        required: true
      country_id:
        type: integer
        foreignTable: country
        foreignReference: id
        required: true
      _indexes:
        country: [country_id]

  Orientation:
    tableName:  orientation
    description: Define una orientacion que podra asociarse a una carrera
    columns:
      id:
      name:
        description:      Nombre de la materia
        type:             varchar(255)
        required:         true

  SubOrientation:
    tableName: sub_orientation
    description: Define una sub orientacion que podra asociarse a una carrera
    columns:
      id:
      name:
        description:      Nombre de la materia
        type:             varchar(255)
        required:         true
      orientation_id:
        type: integer
        foreignTable: orientation
        foreignReference: id
        required: true
        onDelete: cascade
        onUpdate: cascade

  Shift:
    tablename:            shift
    description:          Representa un turno elegible por alumnos
    columns:
      id:
      name:
        type:             varchar(255)
        required:         true

  StudentStudy:
    tableName:            student_study
    description:          Representa un estudio cursado por el alumno
    columns:
      id:
      student_id:
        type: integer
        foreignTable: student
        foreignReference: id
        required: true
        primaryKey: true,
        onDelete: cascade
      study_id:
        type: integer
        foreignTable: study
        foreignReference: id
        required: true
        primaryKey: true
        onDelete: cascade

  Study:
    tableName:            study
    description:          Representa un estudio cursado
    columns:
      id:
      name:
        type: varchar(255)
        required: true
        index: unique

  Occupation:
    columns:
      id:
      name:
        type: varchar(256)
        required: true
      _uniques:
        name: [name(20)]

  OccupationCategory:
    columns:
      id:
      name:
        type: varchar(256)
        required: true
      _uniques:
        name: [name(20)]

  Classroom:
    columns:
      id:
      name:
        type: varchar(255)
        required: true
        index: unique
      seat_number:
        type: integer
        required: false

  Resources:
    columns:
      id:
      name:
        type: varchar(255)
        required: true
        index: unique

  ClassroomResources:
    columns:
      id:
      resource_id:
        type: integer
        foreignClass: Resources
        foreignReference: id
        required: true
        primaryKey: true,
        onDelete: cascade
      classroom_id:
        type: integer
        foreignTable: classroom
        foreignReference: id
        required: true
        primaryKey: true,
        onDelete: cascade

  sfGuardUserProfile:
    tablename:      sf_guard_user_profile
    description:    Representa el perfil de un usuario
    columns:
      id:
      user_id:
        type: integer
        foreignTable: sf_guard_user
        foreignReference: id
        required: true
        onDelete: restrict
      first_name:
        type: varchar(255)
      last_name:
        type: varchar(255)
      identification_type:
        type: 		   integer
        required: 	   true
      identification_number:
        type: 		   varchar(20)
        required: 	   true
      email:
        type: varchar(255)
      phone:
        type: varchar(255)
      observations:
        type: longvarchar
        required:     false

  Conduct:
    tablename:      conduct
    description:    Representa la conducta (muy buena, buena, regular, mala)
    columns:
      id:
      name:
        type: varchar(255)
        required: true
      short_name:
        type: varchar(255)
        required: true
      shift_id:
        description:      Especifica el turno del usuario en un año lectivo
        type:             integer
        foreignTable:     shift
        foreignReference: id
        onUpdate:         cascade
        onDelete:         restrict
        required:         false 

  Holiday:
    tableName: holiday
    description:          Cada tupla representa un día feriado
    columns:
      id:
      day:
        required: true
        type: date
      description:
        required: false
        type: varchar(50)

  OriginSchool:
    tableName:            origin_school
    description:          Representa una escuela primaria de la que provienen los alumnos
    columns:
      id:
      name:
        type: varchar(255)
        required: true
      email:
        type: varchar(80)
        required: true
      phone:
        type: varchar(25)
        required: true
      cue:
        type: integer
        required: true
      sector:
        description:      0=Estatal, 1=Privado, 2=Activo, 3=Social/Cooperativa
        type: integer
        required: true
      field:
        description:      0=Rural, 1=Urbano
        type: integer
        required: true
      address:
        type: varchar(255)
      city_id:
        type: integer
        foreignClass: city
        foreignReference: id
        required: true     
      _indexes:
        cue: [cue]
        city: [city_id]
  
  LetterMark:
    tablename:        letter_mark
    description:      Representa la referencia de letras a numeros
    columns:
      id:
      letter:
        type: varchar(255)
        required: true
      value:
        type: integer
        required: true

  LetterMarkAverage:
    tablename:        letter_mark_average
    description:
    columns:
      id:
      letter_mark_1:
        type: integer
        required: true
      letter_mark_2:
        type: integer
        required: true
      letter_mark_3:
        type: integer
        required: true
      letter_mark_average:
        type: integer
        required: true


