index:
  credentials: [show_student_disciplinary_sanction]

new:
  credentials: [new_student_disciplinary_sanction]

create:
  credentials: [new_student_disciplinary_sanction]

edit:
  credentials: [edit_student_disciplinary_sanction]

update:
  credentials: [edit_student_disciplinary_sanction]

delete:
  credentials: [delete_student_disciplinary_sanction]

