generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           Resources
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          resources
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        batch_actions:      []
        display:            [name]
        object_actions:
          _edit:
          _delete:
        actions:
          _new:
            label: Nuevo recurso
      filter:
          class: false
      form:    ~
      edit:
        actions:
          _list:
            label:              Volver al listado
          _save_and_list:
            label:              Guardar recurso
      new:
        actions:
          _list:
            label:              Volver al listado
          _save_and_list:
            label:              Guardar recurso
          _save_and_add:
            label:              Guardar y agregar otro recurso