generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           Resources
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          resources
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        display: [name]
        object_actions:
          _edit:
          _delete:
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
