generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           SubOrientation
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sub_orientation
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        title: Sub orientations
        display: [name]
        object_actions:
          _edit:
            credentials: [edit_sub_orientation]
          _delete:
            credentials: [edit_sub_orientation]
            condition:   canBeDeleted
        batch_actions: []
        actions:
          back:
            action: back
          _new:
            label:  Nueva
      filter:
        class: false
      form:    ~
      edit:
        title: Edit sub orientation
        actions:
          _list:
            label:              Volver al listado
          _save_and_list:
            label:              Guardar
      new:
        title: New sub orientation
        actions:
          _list:
            label:              Volver al listado
          _save_and_list:
            label:              Guardar
