generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           sfGuardGroup
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_group
    with_propel_route:     1

    config:
      fields:
        description:
          label: Descripción

      list:
        title: Listado de grupos de usuarios
        display: [name, description]
        batch_actions: []
        object_actions:
          _show:
            credentials: [show_group]
          _edit:
            credentials: [edit_group]
          _delete:
            credentials: [edit_group]
        actions:
          _new:
            label:       Nuevo grupo de usuarios
            credentials: [edit_group]

      edit:
        title: Editar grupo de usuarios
        actions:
          _list:
            label:          Volver al listado
          _save_and_list:
            label:          Guardar grupo de usuarios
      new:
        title: Crear grupo de usuarios
        actions:
          _list:
            label:          Volver al listado
          _save_and_list:
            label:          Guardar grupo de usuarios
          _save_and_add:
            label:          Guardar y agregar otro grupo de usuarios
      show:
        title: Detalles del grupo de usuarios
        display: [name, description, _sf_guard_user_group_list, _sf_guard_group_permission_list]
        actions:
          _list:
            label:          Volver al listado
