generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           sfGuardGroup
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_group
    with_propel_route:     1

    config:
      fields:
        description:
          label: Descripción

      list:
        title: Listado de grupos de usuarios
        display: [name, description]
        batch_actions: []
        object_actions:
          _edit:
            credentials: [edit_group]
          _delete:
            credentials: [edit_group]
            
          _show:
            credentials: [show_group]
        actions:
          _new:
            label:          Nuevo grupo de usuarios
            credentials: [edit_group]

      edit:
        title: Editando grupo "%%name%%"
        actions:
          _delete:
            credentials: [edit_group]
          _list:
            label:          Volver al listado de grupos de usuarios
          _save:
          _save_and_add:

      new:
        title: Crear nuevo grupo de usuarios
        actions:
          _list:
            label:          Volver al listado de grupos de usuarios
          _save_and_list:
          _save_and_add:

      show:
        title: Ver grupo "%%name%%"
        display: [name, description, _sf_guard_user_group_list, _sf_guard_group_permission_list]
        actions:
          _list:
            label:          Volver al listado de grupos de usuarios
