index:
  credentials: [edit_justification_type]

new:
  credentials: [edit_justification_type]

create:
  credentials: [edit_justification_type]

edit:
  credentials: [edit_justification_type]

update:
  credentials: [edit_justification_type]

show:
  credentials: [edit_justification_type]

delete:
  credentials: [edit_justification_type]
