students:
  credentials: [show_career]

subjects:
  credentials: [edit_career]

subjectOptions:
  credentials: [edit_career]

careerView:
  credentials: [show_career]

copy:
  credentials: [edit_career]

index:
  credentials: [show_career]

new:
  credentials: [edit_career]

create:
  credentials: [edit_career]

edit:
  credentials: [edit_career]

update:
  credentials: [edit_career]

show:
  credentials: [show_career]

delete:
  credentials: [edit_career]
