generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           Book
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          book
    with_propel_route:     1

    config:
      actions: ~
      fields:
        name:
          label:           Nombre
      list:
        title:             Libros de actas
        display:           [name, description, is_active]
        object_actions:
          _edit:
            credentials:   [edit_book]
          _delete:
            credentials:   [edit_book]
            condition:     canBeDeleted
        batch_actions:     []
        actions:
          _new:
            label:         Nuevo libro
            credentials:   [edit_book]
      filter:
        class:             false
      form:
      edit:
        title:             Editar libro
        actions:
          _list:
            label:         Volver al listado
          _save_and_list:
            label:         Guardar
      new:
        title:             Nuevo libro
        actions:
          _list:
            label:         Volver al listado
          _save_and_list:
            label:         Guardar
          _save_and_add:
            label:         Guardar y agregar otro libro
