generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           CareerSchoolYear
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          equivalence
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        title:      Carreras del año lectivo
        display:    [career]
        object_actions:
          equivalence:
            action:         makeUpEquivalence
            label:          Cargar equivalencias
            credentials:    [show_school_year]

      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
