generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           Course
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          course
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        display:           [name]
        layout:             stacked
        params:             |
          %%_course_info%%
        batch_actions: []
        object_actions:

          _edit:
            condition:      canBeEdited
            credentials:    [edit_course]

          students:
            label:          Listado de estudiantes
            action:         students
            condition:      canListStudents
            credentials:    [show_course]

#          manage_course_days:
#            action:         manageCourseDays
#            label:          Manage course days
#            credentials:    [edit_course]
#            condition:      canManageCourseDays

          teachers:
            action:       courseTeachers
            credentials:  [edit_course]

          preceptors:
            action:       preceptors
            credentials:  [edit_course_preceptors]

          manage_students:
            action:         courseSubjectStudent
            credentials:    [edit_course]
            condition:      canCourseSubjectStudent

          manage_students_regularity:
            action:         courseSubjectStudentsRegularity
            credentials:    [edit_course]
            condition:      canManageStudentsRegularity

          califications:
            action: califications
            credentials: [edit_division_course_califications]
            condition:      canCalificate

          _delete:
            condition:      canBeDeleted
            credentials:    [edit_course]

        actions:
          _new:
            credentials: [new_course]
            label:        Nuevo curso
      filter:
        class: false
      form:    ~
      edit:
        actions:
          _list:
            label:        Volver al listado de cursos
          _save_and_list:
            label:        Guardar y volver al listado de cursos
      new:
        actions:
          _list:
            label:        Volver al listado de cursos
          _save_and_list:
            label:        Guardar y volver al listado de cursos
          _save_and_add:
            label:        Guardar y agregar otro curso
      show:
        actions:
          _back:
            label:              Volver
