generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           Occupation
    theme:                 extended
    non_verbose_templates: true
    with_show:             true
    singular:              ~
    plural:                ~
    route_prefix:          occupation
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        title: Listado de ocupaciones
        batch_actions:      []
        display: [name]
        object_actions:
          _edit:
            credentials: [edit_occupation]
          _delete:
            credentials: [edit_occupation]
            condition:    canBeDeleted
        actions:
          _new:
            label: Nueva ocupación
            credentials: [show_occupation]
      filter:  
        class: false
      form:    ~
      edit:
        title: Editar ocupación
        actions:
          _list:
            label: Volver al listado de ocupaciones
          _save_and_list:
            label: Guardar ocupación
      new:
        title: Nueva ocupación
        actions:
          _list:
            label: Volver al listado de ocupaciones
          _save_and_list:
            label: Guardar ocupación
          _save_and_add:
            label: Guardar y agregar otra ocupación
