generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           SanctionType
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sanction_type
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        display:           [name, considered_in_report_card]
        object_actions:
          _edit:
            credentials:   [edit_disciplinary_sanction_type]
          _delete:
            credentials:   [new_disciplinary_sanction_type]
        batch_actions:     []
        actions:
          _new:
            label: Nuevo tipo de sanci贸n
            credentials:   [new_disciplinary_sanction_type]
      filter:
        class:             false
      form:    ~
      edit:
        actions:
          _list:
            label:              Volver al listado
          _save_and_list:
            label:              Guardar tipo de sanci贸n
      new:
        actions:
          _list:
            label:              Volver al listado
          _save_and_list:
            label:              Guardar tipo de sanci贸n
          _save_and_add:
            label:              Guardar y agregar otro tipo de sanci贸n
