generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           CourseSubject
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          shared_course_subject
    with_propel_route:     1

    config:
      actions: ~
      fields:  ~
      list:
        display: [division, career, subject, count_hours, count_students]
        object_actions: []
        batch_actions: []
        actions:
          _user_export:
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
      exportation:
        enabled: true
        title: Courses of %teacher%
        type: xls
        fieldSelection:
          division:
            label: Division
            method: getDivision
            decorator: text
          career:
            label: Career
            method: getCareer
            decorator: text
          subject:
            label: Subject
            method: getSubject
            decorator: text
          count_hours:
            label: Count hours
            method: getCountHours
            decorator: text
          count_students:
            label: Count students
            method: getCountStudents
            decorator: text          
