generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:           CareerSubject
    theme:                 extended
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          career_subject
    with_propel_route:     1

    config:
      actions: ~

      fields:
        career_id:        {label: Carrera}
        career:           {label: Carrera}
        subject_id:       {label: Materia}
        subject:          {label: Materia}
        year:             {label: Año de la carrera}
        has_options:      {label: Es optativa, help: si tilda esta opción habilitará la asociación de materias opcionales para esta materia}
        has_correlative_previous_year: { label: Todas las materias del año anterior serán correlativas?, help: No tilde esta opción si desea administrar las correlativas en forma manual}
        choices:
          label: Opciones

      list:
        title:  Listado de materias
        sort:              [year, asc]
        display:           [year ]
        layout:             stacked
        params:             |
          %%_career_subject_info%%
        object_actions:
          _edit:
            #condition:      canBeEdited
            credentials: [edit_career_subject]
          _delete:
            #condition:    canBeDeleted
            confirm: La materia que está solicitando borrar puede que sea correlativa de otras materias. ¿Está seguro que desea borrarla?
            credentials: [edit_career_subject]

          add_to_current_career_school_year:
            action: addToCurrentCareerSchoolYear
            confirm:  ¿ Esta seguro de agregar esta materia al año lectivo actual ?
            condition:  canAddToCurrentCareerSchoolYear
            credentials:  [edit_career_subject]

          correlatives:
            label: Correlativas
            action: editCorrelatives
            condition:      canBeEditedCorrelatives
            credentials: [edit_career_subject]

        actions:
          go_back:           {label: Volver al listado de carreras, action: back}
          _new:
            label: Nueva materia
            credentials: [edit_career_subject]
        batch_actions:      []

      filter:
        fields:
          has_options:
            help: ""
      form:    ~

      edit:
        title:              Editar materia
        display:            [career_id, year, subject_id, has_correlative_previous_year, has_options, orientation_id, sub_orientation_id]
        actions:
          _list:
            label:          Volver al listado de materias
          _save_and_list:
            label:          Guardar y volver al listado de materias

      new:
        title:              Agregar materia a %%career%%
        display:            [career_id, year, subject_id, has_correlative_previous_year, has_options, orientation_id, sub_orientation_id]
        actions:
          _list:
            label:          Volver al listado de materias
          _save_and_list:
            label:          Guardar y volver al listado de materias
          _save_and_add:
            label:          Guardar y agregar otra materia
