index:
  credentials: [show_student_office]

new:
  credentials: [edit_student_office]

create:
  credentials: [edit_student_office]

edit:
  credentials: [edit_student_office]

update:
  credentials: [edit_student_office]

show:
  credentials: [show_student_office]

delete:
  credentials: [edit_student_office]

personActivation:
  credentials: [edit_student_office]
