generator:
  class: sfPropelRevisitedGenerator
  param:
    model_class:            Subject
    theme:                  extended
    non_verbose_templates:  true
    with_show:              false
    singular:               ~
    plural:                 ~
    route_prefix:           subject
    with_propel_route:      1

    config:
      actions: ~

      fields:
        name:               {label: Nombre}
        fantasy_name:       {label: Nombre de fantasía}

      list:
        title: Listado de Materias
        display:            [name, fantasy_name ]
        batch_actions:      {}
        actions:
          _new:
            label: Nueva materia
            credentials:    [edit_subject]
        object_actions:
          _edit:
            credentials:    [edit_subject]
          _delete:
            credentials:    [edit_subject]
            condition:      canBeDeleted
      filter:  ~
      form:    ~
      edit:
        title: Editar materia
        actions:
          _list:
            label:          Volver al listado
          _save_and_list:
            label:          Guardar materia
      new:
        title: Nueva materia
        actions:
          _list:
            label:          Volver al listado
          _save_and_list:
            label:          Guardar materia
          _save_and_add:
            label:          Guardar y agregar otra materia
